version: '3.4'

services:
  authservice:
    image: ${DOCKER_REGISTRY-}authapi
    networks:
        - backend
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile

networks:
  backend:
    name: backend
    external: true
    driver: bridge